### ISSUE TITLE
There may be some error in mvf_analyze_dna.py

### ISSUE THREAD

**Issue by PEHGP** [jbpease/mvftools#1]
Dear James,

We estimated the D-statistic value of our population genomic data using the program mvf_tools, while a few errors were reported as followed.
142 line:self.data[trio][contig][val] += 1 --->self.data[trio][contig][val-1] += 1
143 line: self.write(self) ----> self.write()
149 line:self.contigs --->self.params['contigs']
162 line:self.data[trio][contig] --->self.data[trio]
In addition,somtimes DstatComb report ZeroDivisionError
DstatComb may not use 'widows' parameter.

We hope you to help us with the program.

**Comment by jbpease** [comment]
Hello,

Thanks for letter me know.  I just pushed a new version with these bugs fixed.  Please let me know if you run into anything else.

James
