### ISSUE TITLE
Filter mincoverage not behaving as it should

### ISSUE THREAD

**Issue by MafaldaSFerreira** [jbpease/mvftools#4]
Hello,

I've using mvftools (version 2017-06-24; my python version is 2.7) to filter out positions that do not have information for a minimum number of individuals (in this case, 16). My alignment has 49 individuals, including a reference. I noticed that mincoverage it's not working as it should. 

Example 1: 
I have a fasta alignment with 49 individuals (ncol=49) where all dna sequences, except some part of the reference, have missing data (coded as 'N'). When I convert my fasta to mv using the command
`~/mvftools/fasta2mvf.py --fasta chr_10.9850001-9900000_new.fasta --out chr_10.9850001-9900000_new.fasta_test.mvf --reflabel OryCun`
this becomes coded (correctly) as so (I'm showing here position 350 and surrounding positions):
`grep -A10 -B10 '0:350' chr_10.9850001-9900000_new.fasta_test.mvf`
0:340 CX
0:341 GX
0:342 GX
0:343 CX
0:344 CX
0:345 TX
0:346 CX
0:347 AX
0:348 AX
0:349 GX
0:350 X
0:351 X
0:352 X
0:353 X
0:354 X
0:355 X
0:356 X
0:357 X
0:358 X
0:359 X
0:360 X

Then, I try to apply a mincoverage filter for 16: 
`~/mvftools/mvf_filter.py --mvf chr_10.9850001-9900000_new.fasta_test.mvf --out chr_10.9850001-9900000_new.fasta_test.mvf_filter.mvf --actions mincoverage:16`

This is what the output looks like:
`grep -A10 -B10 '0:350' chr_10.9850001-9900000_new.fasta_test.mvf_filter.mvf `
#s LTM_FIN_2192 
#s LTM_KOL_1855 
#s LTM_MAG_1862 
#s LTM_SUI_3121 
#s LTW_JRRK_3 
#s LTW_MTA_3280 
#s PFR_Pen03 
#s SBA_1683_HEART 
#s SFL_2307 
#c 0 label=UNK0 length=549 
0:350 X
0:351 X
0:352 X
0:353 X
0:354 X
0:355 X
0:356 X
0:357 X
0:358 X
0:359 X
0:360 X

In this case, it seems that when all the positions are N, including the reference, mvftools does not remove the position. In this particular case, the expected behavior would be to end up with an empty mvf file, given only the reference has information for some of the positions. 

Example 2: 
This is another example, where I have a mix between positions with just Ns but the reference, or coverage above 16. 

`~/mvftools/fasta2mvf.py --fasta chr_10.31250001-31300000_new.fasta --out chr_10.31250001-31300000_new.fasta_test.mvf --reflabel OryCun`

`grep -A10 -w -B10 '0:10' chr_10.31250001-31300000_new.fasta_test.mvf`
#c 0 label=UNK0 length=3984 
0:1 CX
0:2 TX
0:3 TX
0:4 AX
0:5 AX
0:6 TX
0:7 CX+C3
0:8 TX+T3
0:9 AX+G3
0:10 CX+C3
0:11 AX
0:12 CX
0:13 CX
0:14 AX
0:15 CX
0:16 AX
0:17 GX
0:18 CX
0:19 CX
0:20 CX

position 0:175 has sufficient coverage to pass the filter
`grep -A10 -w -B10 '0:175' chr_10.31250001-31300000_new.fasta_test.mvf`
0:165 CXXCCCCCCXCCCCXCCXXCXCXCCCCCXCCCCXCXXXCCCXXCCXCCX
0:166 TXXTTTTTTXTTTTXTTXXTXTXTTTTTXTTTTXTTXTTTTXXTTXTTX
0:167 AXXAAAAAAXAAAAXAAXXAXAXAAAAAXAAAAXAAXAAAAXXAAXAAX
0:168 AXXAAAAAAXAAAAXAAXAAXAXAAAAAXAAAAXAAXAAAAXXAAXAAX
0:169 CXXCCCCCCXCCCCXCCXCCXCXCCCCCXCCCCXCCXCCCCXXCCXCCX
0:170 TXXTTTTTTTTTTTXTTXXTXTXTTTTTXTTTTXTTXTTTTXXTTXTTX
0:171 TXXTTTTTTTTTTTXTTXXTXTXTTTTTXTTTTXTTXTTTTXXTTXTTX
0:172 CXXTTTTTTTTTTTXTTXXTXTXTTTTTXTTTTXTTXTTTTXXTTXCCX
0:173 CXXCCCCCCCCCCCXCCXXCXCXCCCCCXCCCCXCCXCCCCXXCCXCCX
0:174 AXXAAAAAAAAAAAXAAXXAXAXAAAAAXAAAAXAAXAAAAXXAAXAAX
0:175 TXXTTTTTCTTTTTXTTXXTXTXTTTTTXTTTTXTTXTTTTXXTTXTTX
0:176 GXXGGGGGGGGGGGXGGXXGXGXGGGGGXGGGGXGGXGGGGXXGGXGGX
0:177 CXXCCCCCCCCCCCXCCXXCXCXCCCCCXCCCCXCCXCCCCXXCCXCCX
0:178 TXXTTTTTTTTTTTTTTXXTXTXTTTTTXTTTTXTTXTTTTXXTTXTTX
0:179 AXXAAAAAAAAAAAAAAXAAXAXAAAAAXXAAAXAAAAAAAXXAAXAAX
0:180 TXXTTTTTTTTTTTTTTXTTXTXTTTTTXTTTTXTTTTTTTXXTTXTTX
0:181 AXXAAAAAAAAAAAAAAXAAXAXAAAAAXAAAAXAAAAAAAXXAAXAAX
0:182 TXXTTTTTTTTTTTTTTXTTXTXTTTTTXTTTTXTTTTTTTXXTTXTTX
0:183 TXXTTTTTTTTTTTTTTXTTXTXTTTTTXTTTTXTTTTTTTXXTTXTTX
0:184 AXXAAAAAAAAAAAAAAXAAXAXAAAAAXAAAAXAAAAAAAXXAAXAAX
0:185 TXXTTTTTTTTTTTTTTXTTXTXTTTTTXTTTTXTTTTTTTXXTTTTTX

And this is how these areas look after I apply the same filter:
`~/mvftools/mvf_filter.py --mvf chr_10.31250001-31300000_new.fasta_test.mvf --out chr_10.31250001-31300000_new.fasta_test.mvf_filter --actions mincoverage:16`
`grep -A10 -w -B10 '0:10' chr_10.31250001-31300000_new.fasta_test.mvf_filter `
#s LTM_SUI_3121 
#s LTW_JRRK_3 
#s LTW_MTA_3280 
#s PFR_Pen03 
#s SBA_1683_HEART 
#s SFL_2307 
#c 0 label=UNK0 length=3984 
0:7 CX+C3 **should have been removed**
0:8 TX+T3 **should have been removed**
0:9 AX+G3 **should have been removed**
0:10 CX+C3 **should have been removed**
0:42 TX+T37 **should have been removed**
0:104 TXXTTTTTTXXTXXXTXXXXXXXXTTXXXXTXTXXXXTXTTXXXXXXXX   **<- 33 X**
0:105 CXXCCCCCCXXCXXXCXXXXXXXXCCXXXXCXCXXXXCXCCXXXXXXXX
0:106 TXXTTTTTTXXTXXXTXXXXXXXXTTXXXXTXTXXXXTXTTXXXXXXXX
0:107 GXXGGGGGGXXGXXXGXXXXXXXXGGXXXXGXGXXXXGXGGXXXXXXXX
0:108 AXXAAAAAAXXAXXXAXXXXXXXXAAXXXXAXAXXXXAXAAXXXXXXXX
0:109 GXXGGGGGGXXGXXXGXXXXXXXXGGXXXXGXGXXXXGXGGXXXXXXXX
0:110 CXXCCCCCCXXCXXXCXXXXXXXXCCXXXXCXCXCXXCXCCXXXXXXXX
0:111 TXXTTTTTTXXTTXXTXXXXXXXXTTXXXXTXTXTXXTXTTXXXXXXXX
0:112 GXXGGGGGGXXGGXXGXXXXXXXXGGXXXXGXGXGXXGXGGXXXXXXXX

0:165 CXXCCCCCCXCCCCXCCXXCXCXCCCCCXCCCCXCXXXCCCXXCCXCCX **<-17 X**
0:166 TXXTTTTTTXTTTTXTTXXTXTXTTTTTXTTTTXTTXTTTTXXTTXTTX
0:167 AXXAAAAAAXAAAAXAAXXAXAXAAAAAXAAAAXAAXAAAAXXAAXAAX
0:168 AXXAAAAAAXAAAAXAAXAAXAXAAAAAXAAAAXAAXAAAAXXAAXAAX
0:169 CXXCCCCCCXCCCCXCCXCCXCXCCCCCXCCCCXCCXCCCCXXCCXCCX
0:170 TXXTTTTTTTTTTTXTTXXTXTXTTTTTXTTTTXTTXTTTTXXTTXTTX
0:171 TXXTTTTTTTTTTTXTTXXTXTXTTTTTXTTTTXTTXTTTTXXTTXTTX
0:172 CXXTTTTTTTTTTTXTTXXTXTXTTTTTXTTTTXTTXTTTTXXTTXCCX
0:173 CXXCCCCCCCCCCCXCCXXCXCXCCCCCXCCCCXCCXCCCCXXCCXCCX
0:174 AXXAAAAAAAAAAAXAAXXAXAXAAAAAXAAAAXAAXAAAAXXAAXAAX
0:175 TXXTTTTTCTTTTTXTTXXTXTXTTTTTXTTTTXTTXTTTTXXTTXTTX
0:176 GXXGGGGGGGGGGGXGGXXGXGXGGGGGXGGGGXGGXGGGGXXGGXGGX
0:177 CXXCCCCCCCCCCCXCCXXCXCXCCCCCXCCCCXCCXCCCCXXCCXCCX
0:178 TXXTTTTTTTTTTTTTTXXTXTXTTTTTXTTTTXTTXTTTTXXTTXTTX
0:179 AXXAAAAAAAAAAAAAAXAAXAXAAAAAXXAAAXAAAAAAAXXAAXAAX
0:180 TXXTTTTTTTTTTTTTTXTTXTXTTTTTXTTTTXTTTTTTTXXTTXTTX
0:181 AXXAAAAAAAAAAAAAAXAAXAXAAAAAXAAAAXAAAAAAAXXAAXAAX
0:182 TXXTTTTTTTTTTTTTTXTTXTXTTTTTXTTTTXTTTTTTTXXTTXTTX
0:183 TXXTTTTTTTTTTTTTTXTTXTXTTTTTXTTTTXTTTTTTTXXTTXTTX
0:184 AXXAAAAAAAAAAAAAAXAAXAXAAAAAXAAAAXAAAAAAAXXAAXAAX
0:185 TXXTTTTTTTTTTTTTTXTTXTXTTTTTXTTTTXTTTTTTTXXTTTTTX

I highlighted some lines that should have been removed also... So, is mvftools just removing positions where just the reference has information? Is there something I'm missing?

**Comment by MafaldaSFerreira** [comment]
I've since changed by default python to 3.5 and I observe the same behavior

**Comment by jbpease** [comment]
Hello,

I would strongly recommend upgrading to the latest version of MVFtools on the master branch.  This should be Version 0.5.1.3.  Python3 is strongly recommended, as behavior of some modules is unpredictable on Python2.

The new syntax for your command would be
`~/mvftools/mvftools.py Fasta2MVF --fasta chr_10.9850001-9900000_new.fasta --out chr_10.9850001-9900000_new.fasta_test.mvf --reflabel OryCun`

`~/mvftools/mvftools.py FilterMVF --mvf chr_10.31250001-31300000_new.fasta_test.mvf --out chr_10.31250001-31300000_new.fasta_test.mvf_filter --actions mincoverage:16`

James
