### ISSUE TITLE
CalcPatternCount error

### ISSUE THREAD

**Issue by ceposadap** [jbpease/mvftools#6]
Hi James,

After your recent update to mvftools I managed to convert my vcfs to mvfs. I then proceeded to use CalcPatternCount as you told me to prepare the input for d-foil. However, I find an error. I've already tried asking for more RAM, but I don't know if that's the problem. Do you have ideas about what may be happening? The error message follows:

Traceback (most recent call last):
  File "/home/carlos.posada/data/scripts/mvftools-master/mvftools.py", line 903, in <module>
    MVFcall()
  File "/home/carlos.posada/data/scripts/mvftools-master/mvftools.py", line 88, in __init__
    getattr(self, args.command)()
  File "/home/carlos.posada/data/scripts/mvftools-master/mvftools.py", line 492, in CalcPatternCount
    mvfanalysis.calc_pattern_count(args)
  File "/datacnmat01/biologia/biologia.evolutiva/carlos.posada/scripts/mvftools-master/pylib/mvfanalysis.py", line 280, in calc_pattern_count
    for x in range(0, 2 ** nsamples, 2)])
MemoryError

Thank you,
Carlos

**Comment by jbpease** [comment]
This does appear to be a memory allocation error.  How large is the MVF file you are analyzing, and how many columns and entries does it contain?

James

**Comment by ceposadap** [comment]
Hi James. Thank you for replying. The mvf has a size of 1.7 Gb, 57 columns and samples. Isn't that common?

Carlos

**Comment by jbpease** [comment]
Hi Carlos,
This does seem like a reasonable size for most systems in terms of a memory limit.  
It does occur to me though, that if you are doing a pattern count on all 57 samples at once, that means there are 2^57 = 1.4x10^17 possible patterns.  Usually for patterncount, I only do this on a smaller subset of columns.  If there is sufficient variation across all 57 columns, there must just be too many patterns to count the whole set at once.

James
